spring:
  h2:
    console:
      enabled: true
      path : /console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dataSource
    username: sa
    password:

  jpa:
    show-sql: true
    database: h2
 #   database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql : true
        use_sql_comments : true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
     